# Generated by Django 3.2.13 on 2022-06-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amostras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amostra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField()),
                ('nome_amostra', models.TextField()),
                ('data_liberacao', models.DateField()),
                ('exame_direto', models.TextField()),
                ('metodo_sheaters', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
